document.addEventListener("DOMContentLoaded",()=>{let e=JSON.parse(localStorage.getItem("abo0odiCart"))||[],t=document.getElementById("cart-modal"),n=document.getElementById("cart-overlay"),r=document.getElementById("open-cart-btn"),i=document.getElementById("close-cart-btn"),s=document.getElementById("cart-counter"),a=document.getElementById("cart-items"),c=document.getElementById("cart-total"),l=document.getElementById("checkout-btn"),d=document.getElementById("clear-cart-btn"),o=document.getElementById("all-products-grid"),m=document.getElementById("review-form"),p=document.getElementById("submit-review-btn"),g=document.getElementById("form-message"),v=document.getElementById("reviews-slider"),u=document.getElementById("slide-prev"),y=document.getElementById("slide-next"),f,L=0,h=[],E=document.getElementById("products-dropdown-toggle"),x=document.getElementById("products-dropdown-menu"),w=x.querySelectorAll("a.btn-list");function $(){localStorage.setItem("abo0odiCart",JSON.stringify(e))}function b(){a.innerHTML="";let t=0,n="مرحباً، أرغب في طلب المنتجات التالية:\n\n";0===e.length?(a.innerHTML='<p class="cart-empty-msg">السلة فارغة حالياً.</p>',s.classList.add("hidden")):(s.classList.remove("hidden"),s.textContent=e.length,e.forEach((e,r)=>{t+=e.price,n+=`*${r+1}. ${e.name}*
    - السعر: ${e.price.toFixed(2)} $
`;let i=document.createElement("div");i.classList.add("cart-item"),i.innerHTML=`
                    <div class="cart-item-details">
                        <p class="cart-item-name">${e.name}</p>
                        <p class="cart-item-price">${e.price.toFixed(2)} $</p>
                    </div>
                    <button class="cart-item-remove-btn" data-index="${r}">
                        &times;
                    </button>
                `,a.appendChild(i)})),c.textContent=t.toFixed(2),n+=`
*المجموع الكلي: ${t.toFixed(2)} $*`;let r=encodeURIComponent(n);l.href=`https://wa.me/905061997710?text=${r}`}function _(t){e.push(t),b(),$(),r.style.transform="scale(1.2)",r.style.color="var(--primary)",setTimeout(()=>{r.style.transform="scale(1)",r.style.color="var(--text-color)"},300)}function B(t){e.splice(t,1),b(),$()}function I(){e=[],b(),$(),T()}function M(){t.classList.add("open"),n.classList.add("open")}function T(){t.classList.remove("open"),n.classList.remove("open")}function S(){let e=document.querySelectorAll(".btnproduct");e.forEach(e=>{e.dataset.listenerAttached||(e.dataset.listenerAttached=!0,e.addEventListener("click",e=>{let t=e.target.closest(".product-card"),n=t.querySelector(".product-name").textContent,r=t.querySelector(".price").textContent,i=parseFloat(r.replace(" $","").trim());_({name:n,price:i})}))})}function H(e,t){if(t){if(t.innerHTML="",0===e.length){t.innerHTML='<p style="text-align:center; color: var(--gray); padding: 20px 0;">لا توجد منتجات في هذا القسم حالياً.</p>';return}e.forEach(e=>{let n=e.nameSize&&""!==e.nameSize.trim()?`style="font-size: ${e.nameSize}"`:"",r=e.descSize&&""!==e.descSize.trim()?`style="font-size: ${e.descSize}"`:"",i=`
            <div class="product-card">
              <div class="product-image">
                <img src="${e.imageURL}" alt="${e.name}" />
              </div>
              <div class="product-info">
                <div class="product-name" ${n}>${e.name}</div>
                <div class="product-sub">${e.sub}</div>
                <div class="product-desc" ${r}>${e.desc}</div>
                <div class="product-price">
                  <span class="price">${parseFloat(e.price).toFixed(2)} $</span>
                  <span class="old-price">${e.oldPrice}</span>
                </div>
                <button class="btn btnproduct">أضف إلى السلة</button>
              </div>
            </div>`;t.innerHTML+=i})}}async function C(){try{o&&(o.innerHTML='<p style="text-align:center; font-size: 1.2rem; color: var(--primary);">...جاري تحميل المنتجات...</p>');let e=await fetch("https://docs.google.com/spreadsheets/d/e/2PACX-1vSPa6WPFhppRsBLPOra9BMHHtrooU_sNmWX2eQG7F1EPUTD9MAX3LHT61iqX448Wt2gEchNHWth7Pze/pub?gid=0&single=true&output=csv&_t="+new Date().getTime());if(!e.ok)throw Error("فشل الاتصال بملف البيانات");let t=await e.text(),n=t.split("\n").slice(1),r=n.filter(e=>e&&""!==e.trim()).map(e=>{let[t,n,r,i,s,a,c,l]=e.trim().split(","),d=n?n.trim():"";return{name:t,sub:d,desc:r,price:i,oldPrice:s,imageURL:a,nameSize:c,descSize:l}}).filter(e=>e&&e.name&&""!==e.name.trim());for(let[i,s]of(o&&H(r,o),Object.entries({SM:"sm-grid",PCG:"pcg-grid",MS:"ms-grid",DM:"dm-grid",PCT:"pct-grid",MSF:"msf-grid"}))){let a=r.filter(e=>e.sub.split("|").includes(i)),c=document.getElementById(s);c?H(a,c):console.warn(`لم يتم العثور على شبكة العرض بالـ ID: ${s}`)}S()}catch(l){console.error("حدث خطأ:",l),o&&(o.innerHTML='<p style="text-align:center; font-size: 1.2rem; color: red;">حدث خطأ أثناء تحميل المنتجات. تأكد من صحة الرابط.</p>')}}function P(e){let t="",n=parseInt(e,10);for(let r=1;r<=5;r++)t+=r<=n?'<i class="fas fa-star"></i>':'<i class="fas fa-star empty"></i>';return t}function k(e){if(v.innerHTML="",0===e.length){v.innerHTML='<p style="text-align:center; color: var(--gray); padding: 20px;">لا توجد تقييمات حالياً. كن أول من يضيف تقييم!</p>';return}h=e.slice().reverse();let t="";h.forEach(e=>{let n=P(e.rating),r=new Date(e.timestamp).toLocaleDateString("ar-SA");t+=`
            <div class="review-card">
                <div class="review-card-header">
                    <h3 class="review-card-name">${e.name}</h3>
                    <div class="review-card-rating">${n}</div>
                </div>
                <p class="review-card-comment">${e.comment}</p>
                <div class="review-card-timestamp">${r}</div>
            </div>`}),v.innerHTML=t,z()}function z(){L=0;let e=v.querySelectorAll(".review-card");if(e.length>1){function t(){v.style.transform=`translateX(${100*L}%)`}function n(){L=(L-1+e.length)%e.length,t()}function r(){i(),f=setInterval(n,5e3)}function i(){clearInterval(f)}u.style.display="block",y.style.display="block",y.addEventListener("click",()=>{L=(L+1)%e.length,t(),i()}),u.addEventListener("click",()=>{n(),i()});let s=document.querySelector(".reviews-slider-wrapper");s.addEventListener("mouseenter",i),s.addEventListener("mouseleave",r),r(),t()}else u.style.display="none",y.style.display="none"}async function A(){clearInterval(f);try{v.innerHTML='<p style="text-align:center; color: var(--primary); padding: 20px;">...جاري تحميل التقييمات...</p>';let e=await fetch("https://docs.google.com/spreadsheets/d/e/2PACX-1vSPa6WPFhppRsBLPOra9BMHHtrooU_sNmWX2eQG7F1EPUTD9MAX3LHT61iqX448Wt2gEchNHWth7Pze/pub?gid=169688022&single=true&output=csv&_t="+new Date().getTime());if(!e.ok)throw Error("فشل الاتصال بملف التقييمات");let t=await e.text(),n=t.split("\n").slice(1),r=n.filter(e=>e&&""!==e.trim()).map(e=>{let[t,n,r,i]=e.trim().split(",");return{name:t,rating:n,timestamp:r,comment:i}}).filter(e=>e&&e.name&&e.rating);k(r)}catch(i){console.error("خطأ في جلب التقييمات:",i),v.innerHTML='<p style="text-align:center; color: red; padding: 20px;">حدث خطأ أثناء تحميل التقييمات.</p>'}}r.addEventListener("click",M),i.addEventListener("click",T),n.addEventListener("click",T),d.addEventListener("click",I),a.addEventListener("click",e=>{if(e.target.classList.contains("cart-item-remove-btn")){let t=parseInt(e.target.dataset.index,10);B(t)}}),m.addEventListener("submit",async e=>{e.preventDefault(),p.disabled=!0,p.textContent="...جاري الإرسال...",g.textContent="",g.className="form-message";try{let t=document.getElementById("reviewer-name").value,n=document.getElementById("reviewer-comment").value,r=new FormData(m).get("rating");if(!r||!t||!n)throw Error("الرجاء ملء جميع الحقول (الاسم، التعليق، والنجوم)");await fetch("https://script.google.com/macros/s/AKfycbxRtJxTemuP0SjWjNJuKtExgMntDz-GLdYh_v1zFvWLIaWyUqeJEdbLOxLgDgwSm1C3/exec",{method:"POST",mode:"no-cors",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:t,rating:r,comment:n})}),g.textContent="شكراً لك، تم إرسال تقييمك بنجاح!",g.classList.add("success"),m.reset(),clearInterval(f),setTimeout(A,1e3)}catch(i){console.error("خطأ في إرسال التقييم:",i),g.textContent=i.message.includes("الحقول")?i.message:"حدث خطأ. الرجاء المحاولة مرة أخرى.",g.classList.add("error")}finally{p.disabled=!1,p.textContent="إرسال التقييم"}}),C(),A(),b(),E&&E.addEventListener("click",e=>{e.preventDefault(),x&&x.classList.toggle("show")}),w.forEach(e=>{e.addEventListener("click",()=>{x&&x.classList.remove("show")})}),window.addEventListener("click",e=>{x&&E&&!E.contains(e.target)&&!x.contains(e.target)&&x.classList.remove("show")})});
